import styles from "./index.module.css";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";

export default function Home() {

  return (
    <>
      <Head>
        <title>Authentication App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <div className={styles.container}>
            <AuthShowcase />
        </div>
      </main>
    </>
  );
}

function AuthShowcase() {
  const { data: sessionData } = useSession();

  // const { data: secretMessage } = api.example.getSecretMessage.useQuery(
  //   undefined, // no input
  //   { enabled: sessionData?.user !== undefined }
  // );

  return (
    <>
      <button
        className={styles.loginButton}
        onClick={sessionData ? () => void signOut() : () => void signIn()}
      >
        {sessionData ? "Sign out" : "Sign in"}
      </button>

      <div className={styles.profileContainer}>
        <div className={styles.top}>
          <div>
            <p>Profile</p>
            <p>Some info may be visible to other people</p>
          </div>
          <a href="/edit">Edit</a>
        </div>
        <div>
          <p>Photo</p>
          <img src={sessionData?.user.image} alt="" />
        </div>
        <div>
          <p>Name</p>
          <p>{sessionData?.user.name}</p>
        </div>
        <div>
          <p>Bio</p>
          <p>{sessionData?.user.bio}</p>
        </div>
        <div>
          <p>Phone</p>
          <p>{sessionData?.user.phone}</p>
        </div>
        <div>
          <p>Email</p>
          <p>{sessionData?.user.email}</p>
        </div>
        <div>
          <p>Password</p>
          <p>{sessionData?.user.password}</p>
        </div>
      </div>
</>
  );
}
